### ISSUE TITLE
alignment of synopsis parts

### ISSUE THREAD

**Issue by abathur** [abathur/ldmud-doc#2]
Some (but not all) of our function synopses use an alignment formatting convention in which one or more parts of the synopsis start at a fixed column and are space-padded. You can see a simple example at: https://github.com/ldmud/ldmud/blob/master/doc/efun/attach_erq_demon

My inclination is _not_ to do this (at all) in the source, because it adds overhead to maintaining the doc (i.e., any doc change which requires changing one or more synopsis may require re-aligning each line of the synopsis), but if we think this provides a usability advantage it should be possible to accomplish it in both the HTML and plaintext outputs.

**Comment by zesstra** [comment]
I agree. I would also not do that in the source but leave it to the interpreter creating the output.

**Comment by abathur** [comment]
@zesstra To clarify, you do want to see this argument alignment be a feature of the plaintext and HTML outputs?

**Comment by abathur** [comment]
I have implemented a rudimentary version of this functionality for plaintext and html; you can see at work on both versions of the allocate output:
http://abathur.github.io/ldmud-doc/build/html/efun/allocate.html
https://raw.githubusercontent.com/abathur/ldmud-doc/master/build/plain/efun/allocate
